// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jogrycushdprtzymavtp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpvZ3J5Y3VzaGRwcnR6eW1hdnRwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3MTIwNzIsImV4cCI6MjA3MjI4ODA3Mn0.ImtMR6XySHMVZGnKt04Rfuwrl5LGWgdxToiNv7-Arvw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});